<a href="https://colab.research.google.com/github/pseudo-xy/pseudo-xy/blob/main/pandas_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)


[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [ ]:
import numpy as np
two_dimensional_array = np.array([[1, 2], [3, 4], [5, 6]])
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
df = np.arange(5, 12)
print(df)


[ 5  6  7  8  9 10 11]


In [ ]:
import numpy as np
ds = np.random.random([6])
print(ds)

[0.87649074 0.21392142 0.73835215 0.22686451 0.0807406  0.85679693]


In [ ]:
import numpy as np
df = np.random.randint(low=30, high=90, size=(5))
print(df)

[69 52 48 78 48]


In [ ]:
import numpy as np
feature = np.arange(6, 21)
print(feature)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
label = 3 * (feature) + 4
print(label)

[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [ ]:
noise = (np.random.random([15]) * 4) - 2
print(noise)
label = noise + label
print(label)

[ 0.5170761   0.27861559  0.9170538  -0.47385622  0.696873   -1.18763326
 -0.49213008 -0.42440034  0.83870526 -0.95059582  1.38017968 -0.13894516
 -1.26563209  1.08798442 -0.41447929]
[22.81847117 23.77272123 29.62294705 31.52525498 35.06484096 34.20523203
 38.65406791 42.64810925 45.26005494 49.39592965 53.01575745 53.46215646
 57.39926884 62.85705173 62.24822732]


In [ ]:
import pandas as pd
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])
my_columns_names = ('temperature', 'activity')
my_dataframe = pd.DataFrame(data=my_data, columns=my_columns_names)
print(my_dataframe)

   temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15


In [ ]:
my_dataframe["adjusted"] = my_dataframe["activity"] + 2
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [ ]:
my_dataframe["Region"] = my_dataframe["temperature"] * 2
print(my_dataframe)


   temperature  activity  adjusted  Region
0            0         3         5       0
1           10         7         9      20
2           20         9        11      40
3           30        14        16      60
4           40        15        17      80


In [ ]:
print(my_dataframe.head(3), '\n')

   temperature  activity  adjusted  Region
0            0         3         5       0
1           10         7         9      20
2           20         9        11      40 



In [ ]:
print(my_dataframe.iloc[[2]], '\n')

   temperature  activity  adjusted  Region
2           20         9        11      40 



In [ ]:
my_data = np.random.randint(low=0, high=101, size=(3,4))
columns_names = (["Eleanor", "Chidi", "Tahani", "Jason"])
my_dataframe = pd.DataFrame(data=my_data, columns=columns_names)
my_dataframe['Janet'] = my_dataframe["Jason"] + my_dataframe["Tahani"]
print(my_dataframe)

   Eleanor  Chidi  Tahani  Jason  Janet
0       53      8      61      3     64
1       56     28      63     58    121
2       64     47      31     78    109
